title: Reality...Really?
author: The Voices in Ronnie's Head
email: ronnie@ronnieswafford.com
description: > # this means to ignore newlines until "baseurl:"
  From the perspective of a vetran software developer, grandpa, inventor and writer

# social links
twitter_username: @ronnieswafford
github_username:  @ronnieswafford

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
